--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=1, microseconds=953777), 'exception': None, 'extra': {}, 'file': (name='runner.py', path='D:\\test\\python3.8.9\\lib\\site-packages\\httprunner\\runner.py'), 'function': 'test_start', 'level': (name='INFO', no=20, icon='‚ÑπÔ∏è'), 'line': 453, 'message': 'Start to run testcase: ÁôªÂΩï - Â§±Ë¥•Âú∫ÊôØ, TestCase ID: a88a1c10-4c65-4eb5-b7dd-3a231d196bb6', 'module': 'runner', 'name': 'httprunner.runner', 'process': (id=24864, name='MainProcess'), 'thread': (id=17548, name='MainThread'), 'time': datetime(2023, 7, 19, 23, 59, 43, 330713, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), '‰∏≠ÂõΩÊ†áÂáÜÊó∂Èó¥'))}
Traceback (most recent call last):
  File "D:\test\python3.8.9\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "D:\test\python3.8.9\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "D:\test\python3.8.9\lib\site-packages\colorama\ansitowin32.py", line 47, in write
    self.__convertor.write(text)
  File "D:\test\python3.8.9\lib\site-packages\colorama\ansitowin32.py", line 177, in write
    self.write_and_convert(text)
  File "D:\test\python3.8.9\lib\site-packages\colorama\ansitowin32.py", line 202, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "D:\test\python3.8.9\lib\site-packages\colorama\ansitowin32.py", line 211, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] Âè•ÊüÑÊó†Êïà„ÄÇ
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=1, microseconds=953777), 'exception': None, 'extra': {}, 'file': (name='runner.py', path='D:\\test\\python3.8.9\\lib\\site-packages\\httprunner\\runner.py'), 'function': '__run_step', 'level': (name='INFO', no=20, icon='‚ÑπÔ∏è'), 'line': 295, 'message': 'run step begin: ÁôªÂΩï-Â§±Ë¥• >>>>>>', 'module': 'runner', 'name': 'httprunner.runner', 'process': (id=24864, name='MainProcess'), 'thread': (id=17548, name='MainThread'), 'time': datetime(2023, 7, 19, 23, 59, 43, 330713, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), '‰∏≠ÂõΩÊ†áÂáÜÊó∂Èó¥'))}
Traceback (most recent call last):
  File "D:\test\python3.8.9\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "D:\test\python3.8.9\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "D:\test\python3.8.9\lib\site-packages\colorama\ansitowin32.py", line 47, in write
    self.__convertor.write(text)
  File "D:\test\python3.8.9\lib\site-packages\colorama\ansitowin32.py", line 177, in write
    self.write_and_convert(text)
  File "D:\test\python3.8.9\lib\site-packages\colorama\ansitowin32.py", line 202, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "D:\test\python3.8.9\lib\site-packages\colorama\ansitowin32.py", line 211, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] Âè•ÊüÑÊó†Êïà„ÄÇ
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=2, microseconds=179173), 'exception': None, 'extra': {}, 'file': (name='client.py', path='D:\\test\\python3.8.9\\lib\\site-packages\\httprunner\\client.py'), 'function': 'request', 'level': (name='DEBUG', no=10, icon='üêû'), 'line': 186, 'message': 'client IP: 192.168.3.17, Port: 58173', 'module': 'client', 'name': 'httprunner.client', 'process': (id=24864, name='MainProcess'), 'thread': (id=17548, name='MainThread'), 'time': datetime(2023, 7, 19, 23, 59, 43, 556109, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), '‰∏≠ÂõΩÊ†áÂáÜÊó∂Èó¥'))}
Traceback (most recent call last):
  File "D:\test\python3.8.9\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "D:\test\python3.8.9\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "D:\test\python3.8.9\lib\site-packages\colorama\ansitowin32.py", line 47, in write
    self.__convertor.write(text)
  File "D:\test\python3.8.9\lib\site-packages\colorama\ansitowin32.py", line 177, in write
    self.write_and_convert(text)
  File "D:\test\python3.8.9\lib\site-packages\colorama\ansitowin32.py", line 202, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "D:\test\python3.8.9\lib\site-packages\colorama\ansitowin32.py", line 211, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] Âè•ÊüÑÊó†Êïà„ÄÇ
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=2, microseconds=180215), 'exception': None, 'extra': {}, 'file': (name='client.py', path='D:\\test\\python3.8.9\\lib\\site-packages\\httprunner\\client.py'), 'function': 'request', 'level': (name='DEBUG', no=10, icon='üêû'), 'line': 194, 'message': 'server IP: 124.70.221.221, Port: 8201', 'module': 'client', 'name': 'httprunner.client', 'process': (id=24864, name='MainProcess'), 'thread': (id=17548, name='MainThread'), 'time': datetime(2023, 7, 19, 23, 59, 43, 557151, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), '‰∏≠ÂõΩÊ†áÂáÜÊó∂Èó¥'))}
Traceback (most recent call last):
  File "D:\test\python3.8.9\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "D:\test\python3.8.9\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "D:\test\python3.8.9\lib\site-packages\colorama\ansitowin32.py", line 47, in write
    self.__convertor.write(text)
  File "D:\test\python3.8.9\lib\site-packages\colorama\ansitowin32.py", line 177, in write
    self.write_and_convert(text)
  File "D:\test\python3.8.9\lib\site-packages\colorama\ansitowin32.py", line 202, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "D:\test\python3.8.9\lib\site-packages\colorama\ansitowin32.py", line 211, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] Âè•ÊüÑÊó†Êïà„ÄÇ
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=2, microseconds=181168), 'exception': None, 'extra': {}, 'file': (name='client.py', path='D:\\test\\python3.8.9\\lib\\site-packages\\httprunner\\client.py'), 'function': 'log_print', 'level': (name='DEBUG', no=10, icon='üêû'), 'line': 40, 'message': '\n================== request details ==================\nmethod   : POST\nurl      : http://124.70.221.221:8201/api/v1/login\nheaders  : {\n    "User-Agent": "python-requests/2.28.2",\n    "Accept-Encoding": "gzip, deflate, br",\n    "Accept": "*/*",\n    "Connection": "keep-alive",\n    "HRUN-Request-ID": "HRUN-a88a1c10-4c65-4eb5-b7dd-3a231d196bb6-383331",\n    "Content-Length": "46",\n    "Content-Type": "application/json"\n}\ncookies  : {}\nbody     : {\n    "username": "test123",\n    "password": "1234567"\n}\n', 'module': 'client', 'name': 'httprunner.client', 'process': (id=24864, name='MainProcess'), 'thread': (id=17548, name='MainThread'), 'time': datetime(2023, 7, 19, 23, 59, 43, 558104, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), '‰∏≠ÂõΩÊ†áÂáÜÊó∂Èó¥'))}
Traceback (most recent call last):
  File "D:\test\python3.8.9\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "D:\test\python3.8.9\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "D:\test\python3.8.9\lib\site-packages\colorama\ansitowin32.py", line 47, in write
    self.__convertor.write(text)
  File "D:\test\python3.8.9\lib\site-packages\colorama\ansitowin32.py", line 177, in write
    self.write_and_convert(text)
  File "D:\test\python3.8.9\lib\site-packages\colorama\ansitowin32.py", line 202, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "D:\test\python3.8.9\lib\site-packages\colorama\ansitowin32.py", line 211, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] Âè•ÊüÑÊó†Êïà„ÄÇ
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=2, microseconds=182166), 'exception': None, 'extra': {}, 'file': (name='client.py', path='D:\\test\\python3.8.9\\lib\\site-packages\\httprunner\\client.py'), 'function': 'log_print', 'level': (name='DEBUG', no=10, icon='üêû'), 'line': 40, 'message': '\n================== response details ==================\nstatus_code : 200\nheaders  : {\n    "Date": "Wed, 19 Jul 2023 15:59:51 GMT",\n    "Server": "WSGIServer/0.2 CPython/3.6.8",\n    "Content-Type": "application/json",\n    "Allow": "POST, OPTIONS",\n    "X-Frame-Options": "SAMEORIGIN",\n    "Content-Length": "78",\n    "Vary": "Cookie",\n    "Set-Cookie": "sessionid=2c3n787yvqcbujla2hs7rutga2txpuek; expires=Wed, 02-Aug-2023 15:59:51 GMT; HttpOnly; Max-Age=1209600; Path=/"\n}\ncookies  : {\n    "sessionid": "2c3n787yvqcbujla2hs7rutga2txpuek"\n}\nencoding : utf-8\ncontent_type : application/json\nbody     : {\n    "code": 3003,\n    "msg": "\\u8d26\\u53f7\\u6216\\u5bc6\\u7801\\u4e0d\\u6b63\\u786e",\n    "username": "test123",\n    "token": ""\n}\n', 'module': 'client', 'name': 'httprunner.client', 'process': (id=24864, name='MainProcess'), 'thread': (id=17548, name='MainThread'), 'time': datetime(2023, 7, 19, 23, 59, 43, 559102, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), '‰∏≠ÂõΩÊ†áÂáÜÊó∂Èó¥'))}
Traceback (most recent call last):
  File "D:\test\python3.8.9\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "D:\test\python3.8.9\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "D:\test\python3.8.9\lib\site-packages\colorama\ansitowin32.py", line 47, in write
    self.__convertor.write(text)
  File "D:\test\python3.8.9\lib\site-packages\colorama\ansitowin32.py", line 177, in write
    self.write_and_convert(text)
  File "D:\test\python3.8.9\lib\site-packages\colorama\ansitowin32.py", line 202, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "D:\test\python3.8.9\lib\site-packages\colorama\ansitowin32.py", line 211, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] Âè•ÊüÑÊó†Êïà„ÄÇ
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=2, microseconds=182166), 'exception': None, 'extra': {}, 'file': (name='client.py', path='D:\\test\\python3.8.9\\lib\\site-packages\\httprunner\\client.py'), 'function': 'request', 'level': (name='INFO', no=20, icon='‚ÑπÔ∏è'), 'line': 217, 'message': 'status_code: 200, response_time(ms): 224.4 ms, response_length: 0 bytes', 'module': 'client', 'name': 'httprunner.client', 'process': (id=24864, name='MainProcess'), 'thread': (id=17548, name='MainThread'), 'time': datetime(2023, 7, 19, 23, 59, 43, 559102, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), '‰∏≠ÂõΩÊ†áÂáÜÊó∂Èó¥'))}
Traceback (most recent call last):
  File "D:\test\python3.8.9\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "D:\test\python3.8.9\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "D:\test\python3.8.9\lib\site-packages\colorama\ansitowin32.py", line 47, in write
    self.__convertor.write(text)
  File "D:\test\python3.8.9\lib\site-packages\colorama\ansitowin32.py", line 177, in write
    self.write_and_convert(text)
  File "D:\test\python3.8.9\lib\site-packages\colorama\ansitowin32.py", line 202, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "D:\test\python3.8.9\lib\site-packages\colorama\ansitowin32.py", line 211, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] Âè•ÊüÑÊó†Êïà„ÄÇ
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=2, microseconds=183164), 'exception': None, 'extra': {}, 'file': (name='response.py', path='D:\\test\\python3.8.9\\lib\\site-packages\\httprunner\\response.py'), 'function': 'validate', 'level': (name='INFO', no=20, icon='‚ÑπÔ∏è'), 'line': 246, 'message': 'assert body.code equal 3003(int)\t==> pass', 'module': 'response', 'name': 'httprunner.response', 'process': (id=24864, name='MainProcess'), 'thread': (id=17548, name='MainThread'), 'time': datetime(2023, 7, 19, 23, 59, 43, 560100, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), '‰∏≠ÂõΩÊ†áÂáÜÊó∂Èó¥'))}
Traceback (most recent call last):
  File "D:\test\python3.8.9\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "D:\test\python3.8.9\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "D:\test\python3.8.9\lib\site-packages\colorama\ansitowin32.py", line 47, in write
    self.__convertor.write(text)
  File "D:\test\python3.8.9\lib\site-packages\colorama\ansitowin32.py", line 177, in write
    self.write_and_convert(text)
  File "D:\test\python3.8.9\lib\site-packages\colorama\ansitowin32.py", line 202, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "D:\test\python3.8.9\lib\site-packages\colorama\ansitowin32.py", line 211, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] Âè•ÊüÑÊó†Êïà„ÄÇ
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=2, microseconds=184160), 'exception': None, 'extra': {}, 'file': (name='runner.py', path='D:\\test\\python3.8.9\\lib\\site-packages\\httprunner\\runner.py'), 'function': '__run_step', 'level': (name='INFO', no=20, icon='‚ÑπÔ∏è'), 'line': 307, 'message': 'run step end: ÁôªÂΩï-Â§±Ë¥• <<<<<<\n', 'module': 'runner', 'name': 'httprunner.runner', 'process': (id=24864, name='MainProcess'), 'thread': (id=17548, name='MainThread'), 'time': datetime(2023, 7, 19, 23, 59, 43, 561096, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), '‰∏≠ÂõΩÊ†áÂáÜÊó∂Èó¥'))}
Traceback (most recent call last):
  File "D:\test\python3.8.9\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "D:\test\python3.8.9\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "D:\test\python3.8.9\lib\site-packages\colorama\ansitowin32.py", line 47, in write
    self.__convertor.write(text)
  File "D:\test\python3.8.9\lib\site-packages\colorama\ansitowin32.py", line 177, in write
    self.write_and_convert(text)
  File "D:\test\python3.8.9\lib\site-packages\colorama\ansitowin32.py", line 202, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "D:\test\python3.8.9\lib\site-packages\colorama\ansitowin32.py", line 211, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] Âè•ÊüÑÊó†Êïà„ÄÇ
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=2, microseconds=184160), 'exception': None, 'extra': {}, 'file': (name='runner.py', path='D:\\test\\python3.8.9\\lib\\site-packages\\httprunner\\runner.py'), 'function': 'test_start', 'level': (name='INFO', no=20, icon='‚ÑπÔ∏è'), 'line': 463, 'message': 'generate testcase log: D:\\test\\hrun\\sima_httprunner3\\logs\\a88a1c10-4c65-4eb5-b7dd-3a231d196bb6.run.log', 'module': 'runner', 'name': 'httprunner.runner', 'process': (id=24864, name='MainProcess'), 'thread': (id=17548, name='MainThread'), 'time': datetime(2023, 7, 19, 23, 59, 43, 561096, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), '‰∏≠ÂõΩÊ†áÂáÜÊó∂Èó¥'))}
Traceback (most recent call last):
  File "D:\test\python3.8.9\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "D:\test\python3.8.9\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "D:\test\python3.8.9\lib\site-packages\colorama\ansitowin32.py", line 47, in write
    self.__convertor.write(text)
  File "D:\test\python3.8.9\lib\site-packages\colorama\ansitowin32.py", line 177, in write
    self.write_and_convert(text)
  File "D:\test\python3.8.9\lib\site-packages\colorama\ansitowin32.py", line 202, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "D:\test\python3.8.9\lib\site-packages\colorama\ansitowin32.py", line 211, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] Âè•ÊüÑÊó†Êïà„ÄÇ
--- End of logging error ---
